<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OperatorModdedOperations</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="BepInEx.Core" />
    <Reference Include="BepInEx.Unity.IL2CPP" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="UnityEngine.AssetBundleModule" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="UnityEngine.UI" />
    <Reference Include="Unity.TextMeshPro" />
    <Reference Include="OperatorModAPI" />
    <Reference Include="Il2CppInterop.Runtime" />
    <Reference Include="UnityEngine.TerrainModule" />
    <Reference Include="UnityEngine.TerrainPhysicsModule" />
    <Reference Include="UnityEngine.PhysicsModule" />
    <Reference Include="Il2Cppmscorlib" />
    <Reference Include="Mirror" />
    <Reference Include="UnityEngine.AudioModule" />
    <Reference Include="Unity.RenderPipelines.Core.Runtime" />
    <Reference Include="Unity.RenderPipelines.HighDefinition.Runtime" />
    <Reference Include="AstarPathfindingProject" />
    <Reference Include="UnityEngine.AnimationModule" />
    <Reference Include="UnityEngine.UIModule" />
    <Reference Include="Unity.Localization" />
    <Reference Include="UnityEngine.ImageConversionModule" />
  </ItemGroup>
</Project>